Repository dsrvlabs/vatz, pull requests merged in 2022-12, with the labels that each got.

#311 Add github action golangci-lint
  .github/workflows/golangci-lint.yml
Labels: area:ci/cd, type:enhancement

#317 Install and start plugin by CLI
  cmd/plugin.go
  cmd/plugin_test.go
  go.mod
  go.sum
  manager/plugin/db.go
  manager/plugin/db_test.go
  manager/plugin/plugin.go
  manager/plugin/plugin_test.go
Labels: Vatz, area:svc, type:feature-development

#328 Update installation.md
  docs/installation.md
Labels: Vatz, type:documentation, area:project

#334 Error on send a notification
  .github/workflows/ci_pr_reminder.yaml
Labels: area:ci/cd, type:bug

#345 Add Options in ReqMsg to use unique name in key
  manager/dispatcher/discord.go
  manager/dispatcher/dispatcher.go
  manager/dispatcher/dispatcher_test.go
  manager/dispatcher/pagerduty.go
  manager/dispatcher/telegram.go
  manager/healthcheck/general_healthcheck.go
  manager/types/dispatcher.go
Labels: Vatz, area:svc

#335 List command of plugin
  cmd/plugin.go
  go.mod
  go.sum
  manager/plugin/db.go
  manager/plugin/db_test.go
  manager/plugin/plugin.go
  manager/plugin/plugin_test.go
Labels: Vatz, area:svc, type:feature-development

#343 Applying Prometheus as Node exporter
  cmd/cmd.go
  cmd/init.go
  cmd/start.go
  go.mod
  go.sum
  manager/config/config.go
Labels: Vatz, area:svc, type:feature-development
