Repository dsrvlabs/vatz, pull requests merged in 2023-05, with the labels that each got.

#430 Avoid overriding DB while its on coverage test.
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/init.go
  manager/plugin/plugin.go
  manager/types/cmd.go
Labels: Vatz, area:svc, type:bug

#428 Store a plugin status to not to send notification while VATZ is running when we stop in purpose
  cmd/plugin.go
  cmd/start.go
  manager/plugin/db.go
  manager/plugin/db_test.go
  manager/plugin/plugin.go
  utils/utils.go
Labels: Vatz, area:svc, type:enhancement

#431 State Golang is requirements to run VATZ
  docs/installation.md
  go.mod
Labels: Vatz, type:documentation

#433 Add home path on the config
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/init.go
  cmd/plugin.go
  cmd/plugin_test.go
  cmd/start.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/fixtures.go
  manager/plugin/db.go
  manager/plugin/plugin.go
Labels: Vatz, area:svc, type:enhancement

#438 Add CI about creation discussion w/o labels.
  .github/workflows/create-vatz-bi-weekly.yml
Labels: Vatz, area:ci/cd, type:feature-development

#441 Fix. config instance should be loaded before execute CLI.
  cmd/plugin.go
Labels: Vatz, area:svc, type:bug

#446 Fixed bug about wrong setting Authorization part
  .github/workflows/create-vatz-bi-weekly.yml
Labels: Vatz, area:ci/cd, type:bug

#445 Remove flag `--home` in CLI command `vatz init`
  cmd/cmd_test.go
  cmd/init.go
Labels: Vatz, type:enhancement, type:bug

#459 - Revert back the Home path in CLI that gives user to set their home_…
  cmd/cmd_test.go
  cmd/init.go
Labels: Vatz, area:svc, type:bug
