Repository dsrvlabs/vatz, pull requests merged in 2023-01, with the labels that each got.

#359 Bug fix for PR Reminders
  .github/workflows/ci_pr_notifier.yaml
  .github/workflows/ci_pr_reminder.yaml
  .github/workflows/ci_reamin_pr_reminder.yaml
Labels: Vatz, type:bug

#361 Fix healthcheck msg
  manager/healthcheck/healthcheck.go
Labels: area:svc, type:bug

#355 #322: Redirect plugin's log
  .gitignore
  cmd/plugin.go
  manager/plugin/plugin.go
  manager/plugin/plugin_test.go
Labels: Vatz, area:svc, type:enhancement

#366 Edit README.md (#356)
  README.md
Labels: area:svc, type:documentation, area:project

#364 Add information about monitoring service on VATZ
  docs/design.md
  docs/images/monitoring_as_is.png
  docs/images/monitoring_to_be.png
Labels: Vatz, type:documentation, area:project

#374 Update design.md
  docs/design.md
  docs/images/monitoring_as_is.png
  docs/images/monitoring_to_be.png
Labels: type:documentation, area:project

#371 Update installation.md
  docs/installation.md
Labels: Vatz, area:svc, type:documentation

#373 Update contribution.md
  docs/contributing.md
Labels: Vatz, area:svc, type:feature-development, type:documentation

#377 Add a link for Release Note
  README.md
Labels: Vatz, area:svc, type:documentation

#382 Add Apache 2.0 license
  LICENSE
Labels: Vatz, project_management

#381 Align log format
  cmd/start.go
Labels: area:svc, type:enhancement

#384 Sending A notification PRs from forked repo
  .github/workflows/ci_pr_notifier.yaml
Labels: Vatz, area:ci/cd

#387 CLI - Stop Plugin
  cmd/plugin.go
  go.mod
  go.sum
  manager/plugin/plugin.go
  manager/plugin/plugin_test.go
Labels: Vatz, area:svc, type:feature-development
