Repository dsrvlabs/vatz, pull requests merged in 2023-10, with the labels that each got.

#502 Update python-version on ci_coverage.yml with latest stable version.
  .github/workflows/ci_coverage.yml
Labels: Vatz, area:ci/cd, type:bug

#501 Add log client connected to plugin successfully.
  cmd/start.go
  monitoring/prometheus/metric.go
  monitoring/prometheus/metric_test.go
  monitoring/prometheus/prometheus.go
  monitoring/prometheus/prometheus_test.go
  utils/utils.go
Labels: Vatz, area:svc, type:enhancement

#505 Update SDK to remove AlertTypes in CallResponse in struct
  manager/executor/general_executor.go
  sdk/README.md
  sdk/grpc.go
  sdk/sdk.go
  sdk/sdk_test.go
Labels: area:svc, type:enhancement

#508 Apply the new version of proto
  go.mod
  go.sum
Labels: Vatz, area:svc, type:enhancement

#518 Update documentation - fix typo error and fix broken link
  README.md
  docs/community_plugins.md
Labels: Vatz, area:svc, type:documentation

#516 Update Codes to pass Golint
  Makefile
  cmd/cmd.go
  cmd/init.go
  cmd/plugin.go
  cmd/plugin_test.go
  cmd/start.go
  manager/executor/executor_test.go
  manager/executor/general_executor.go
  manager/healthcheck/general_healthcheck.go
  manager/plugin/db_test.go
  manager/plugin/plugin.go
  manager/plugin/plugin_test.go
  monitoring/prometheus/metric_test.go
  monitoring/prometheus/prometheus.go
  monitoring/prometheus/prometheus_test.go
  rpc/rpc.go
  rpc/rpc_test.go
Labels: Vatz, area:svc, type:feature-development

#513 Throw appropriate error in command of `plugin uninstall` when plugin …
  manager/plugin/plugin.go
Labels: Vatz, type:bug

#514 Stop VATZ process if all notification channels fail to send notifications
  cmd/start.go
  manager/dispatcher/discord.go
  manager/dispatcher/telegram.go
  manager/healthcheck/general_healthcheck.go
  manager/healthcheck/healthcheck_test.go
Labels: Vatz, area:svc, type:enhancement

#522 Add library fmt
  manager/healthcheck/general_healthcheck.go
Labels: Vatz, area:svc, type:bug, type:hotfix

#525 Print ERR failed to set dispatcher: <nil> module=dispatcher even if t…
  manager/executor/general_executor.go
Labels: Vatz, area:svc, type:bug
