Repository dsrvlabs/vatz, pull requests merged in 2023-06, with the labels that each got.

#457 Add new flag `--all` on CLI command `vatz init`
  cmd/init.go
Labels: Vatz, area:svc, type:enhancement

#461 Fix lint in config, dispatcher
  manager/config/config.go
  manager/dispatcher/discord.go
  manager/dispatcher/dispatcher.go
  manager/dispatcher/mock_Dispatcher.go
  manager/dispatcher/pagerduty.go
  manager/dispatcher/telegram.go
  manager/types/dispatcher.go
Labels: Vatz, area:svc

#463 line up in cmd format in init.go
  cmd/init.go
Labels: Vatz, area:svc

#464 Add new license policies and removed apache2.0 license.
  LICENSE
  README.md
Labels: Vatz, type:enhancement, type:documentation

#466 Check the cron entry initialized in dispatcher
  manager/dispatcher/discord.go
  manager/dispatcher/telegram.go
Labels: area:svc, type:bug

#467 Add new license file.
  LICENSE
  LICENSE.LESSER
  README.md
Labels: Vatz, type:documentation

#452 Update documents
  docs/community_plugins.md
  docs/installation.md
Labels: type:documentation, area:project

#455 update CLI example
  cmd/plugin.go
  docs/cli.md
Labels: type:documentation, area:project

#473 fix panic message when all CLI commands fails.
  main.go
Labels: Vatz, type:bug

#472 Update README.md
  README.md
Labels: type:documentation, area:project

#477 Fix version badge on README.md -> v1.0.0-RC.1
  README.md
Labels: Vatz, area:svc, type:hotfix

#476 Fix version & license badge on README.md
  README.md
Labels: Vatz, area:svc, type:bug, type:hotfix
