Repository dsrvlabs/vatz, pull requests merged in 2024-07, with the labels that each got.

#575 Add new discord webhook address type
  manager/dispatcher/discord.go
Labels: type:enhancement

#571 Fix the github action of creation bi weekly discussion
  .github/workflows/create-vatz-bi-weekly.yml
Labels: type: bi-weekly sync, area:project

#569 Add monitoring to GCP cloud Logging
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/init.go
  cmd/plugin.go
  cmd/start.go
  go.mod
  go.sum
  manager/config/config.go
  manager/dispatcher/discord.go
  manager/dispatcher/dispatcher.go
  manager/dispatcher/dispatcher_test.go
  manager/dispatcher/mock_Dispatcher.go
  manager/dispatcher/pagerduty.go
  manager/dispatcher/slack.go
  manager/dispatcher/telegram.go
  manager/executor/executor_test.go
  manager/executor/general_executor.go
  manager/healthcheck/general_healthcheck.go
  manager/healthcheck/healthcheck.go
  manager/healthcheck/healthcheck_test.go
  manager/plugin/plugin.go
  manager/types/cmd.go
  manager/types/healthcheck.go
  mocks/HealthCheck.go
  monitoring/gcp/gcp.go
  monitoring/gcp/gcp_client.go
  rpc/grpc.go
  rpc/rpc_test.go
  types/cmd.go
  types/manager.go
  types/monitoring.go
  utils/cmd.go
  utils/monitoring.go
Labels: Vatz, type:enhancement, V1
